name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check tests
      id: check-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check tests
        setup-command: npm install
        command: npm test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-TESTS_RESULTS: "${{steps.check-tests.outputs.result}}"
      with:
        runners: check-tests
